novels = {
	"A Record of a Mortal’s Journey to Immortality": "rmji",
	"A Will Eternal": "a-will-eternal",
	"Against the Gods": "against-the-gods",
	"Ancient Strengthening Technique": "ancient-strengthening-technique",
	"Archfiend": "archfiend",
	"City of Sin": "city-of-sin",
	"Demon Hunter": "demon-hunter",
	"Desolate Era": "desolate-era",
	"Emperor’s Domination": "emperors-domination",
	"Gate of Revelation": "gate-of-revelation",
	"Heavenly Jewel Change": "heavenly-jewel-change",
	"Imperial God Emperor": "imperial-god-emperor",
	"Invincible": "invincible",
	"Legend of the Dragon King": "legend-of-the-dragon-king",
	"Lord of All Realms": "lord-of-all-realms",
	"Martial God Asura": "martial-god-asura",
	"Martial World": "martial-world",
	"Monarch of Evernight": "monarch-of-evernight",
	"Perfect World": "perfect-world",
	"Rebirth of the Thief Who Roamed the World": "rebirth-of-the-thief-who-roamed-the-world",
	"Renegade Immortal": "renegade-immortal",
	"Skyfire Avenue": "skyfire-avenue",
	"Sovereign of the Three Realms": "sovereign-of-the-three-realms",
	"Spirit Realm": "spirit-realm",
	"Spirit Vessel": "spirit-vessel",
	"Tales of Demons & Gods": "tales-of-demons-and-gods",
	"Talisman Emperor": "talisman-emperor",
	"Terror Infinity": "terror-infinity",
	"The Charm of Soul Pets": "the-charm-of-soul-pets",
	"The Godsfall Chronicles": "the-godsfall-chronicles",
	"The Grandmaster Strategist": "the-grandmaster-strategist",
	"The Great Ruler": "the-great-ruler",
	"The Unrivaled Tang Sect": "the-unrivaled-tang-sect",
	"TranXending Vision": "tranxending-vision",
	"Upgrade Specialist in Another World": "upgrade-specialist-in-another-world",
	"Wu Dong Qian Kun": "wu-dong-qian-kun",
}